"""
storage.py — SQLAlchemy-based tree storage for ApexRAG.

Two tables:
  DocumentNode   — one row per section/leaf in the document tree.
  PageIndexEntry — inverted index: section_title/keyword → node_id + page range.
                   Powers the book-style "page index" endpoint in the FastAPI UI.

Supports both SQLite (local dev) and PostgreSQL (production) via a single
async engine. All DB operations are async-safe, making this compatible with
FastAPI and other async frameworks.

Schema:
    DocumentNode — one row per section/leaf in the document tree.
        id          : auto-incremented primary key
        doc_id      : logical document identifier (file hash or UUID)
        parent_id   : self-referential FK (NULL for root nodes)
        path        : LTree-style string "1.2.3" for fast subtree queries
        title       : heading text extracted from the document
        summary     : 30-word Semantic Map generated by Ollama
        content     : raw section text (NULL for intermediate nodes)
        metadata_   : JSON blob (page numbers, source file, etc.)
        depth       : nesting level (0 = document root)
        position    : sibling order within parent
        page_start  : first page number this section appears on (0 if unknown)
        page_end    : last page number (inclusive)
        created_at  : UTC timestamp

    PageIndexEntry — book-style inverted index entry.
        id          : auto-incremented primary key
        doc_id      : foreign document
        node_id     : the DocumentNode this entry points to
        term        : the heading/keyword being indexed
        page_start  : page range start
        page_end    : page range end
        path        : LTree path of the node for fast lookup
"""

from __future__ import annotations

import json
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Any, AsyncGenerator, Sequence

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    event,
    select,
    asc,
)
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from apex_rag.utils import logger

# ---------------------------------------------------------------------------
# ORM Base & Model
# ---------------------------------------------------------------------------


class Base(DeclarativeBase):
    """Shared declarative base for all ApexRAG ORM models."""


class DocumentNode(Base):
    """
    One node in the document decision tree.

    Intermediate nodes hold section summaries; leaf nodes additionally
    carry the full `content` text that the agent ultimately returns.
    """

    __tablename__ = "document_nodes"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    doc_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    parent_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("document_nodes.id", ondelete="CASCADE"), nullable=True
    )
    path: Mapped[str] = mapped_column(String(512), nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False, default="")
    summary: Mapped[str] = mapped_column(Text, nullable=False, default="")
    content: Mapped[str | None] = mapped_column(Text, nullable=True)
    meta_: Mapped[str] = mapped_column(
        "metadata", Text, nullable=False, default="{}"
    )
    depth: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    page_start: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    page_end: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # Self-referential relationships
    children: Mapped[list["DocumentNode"]] = relationship(
        "DocumentNode",
        back_populates="parent",
        cascade="all, delete-orphan",
        foreign_keys=[parent_id],
        order_by="DocumentNode.position",
        lazy="select",
    )
    parent: Mapped["DocumentNode | None"] = relationship(
        "DocumentNode",
        back_populates="children",
        remote_side=[id],
        foreign_keys=[parent_id],
    )

    # Composite index for efficient subtree queries
    __table_args__ = (
        Index("ix_docnodes_doc_path", "doc_id", "path"),
        Index("ix_docnodes_parent", "parent_id"),
    )

    # -- Convenience properties --------------------------------------------

    @property
    def meta(self) -> dict[str, Any]:
        """Deserialised metadata dict (avoids clash with SQLAlchemy's .metadata)."""
        try:
            return json.loads(self.meta_)
        except (json.JSONDecodeError, TypeError):
            return {}

    @meta.setter
    def meta(self, value: dict[str, Any]) -> None:
        self.meta_ = json.dumps(value, ensure_ascii=False)

    @property
    def is_leaf(self) -> bool:
        """True when this node holds actual document content."""
        return self.content is not None

    @property
    def page_range(self) -> str:
        """Human-readable page range string, e.g. 'p.12–15'."""
        if self.page_start == 0 and self.page_end == 0:
            return ""
        if self.page_start == self.page_end:
            return f"p.{self.page_start}"
        return f"p.{self.page_start}–{self.page_end}"

    def to_dict(self) -> dict[str, Any]:
        """Serialisable representation for the FastAPI index page."""
        return {
            "id": self.id,
            "doc_id": self.doc_id,
            "parent_id": self.parent_id,
            "path": self.path,
            "title": self.title,
            "summary": self.summary,
            "depth": self.depth,
            "position": self.position,
            "page_start": self.page_start,
            "page_end": self.page_end,
            "page_range": self.page_range,
            "is_leaf": self.is_leaf,
            "has_content": self.content is not None,
            "meta": self.meta,
        }

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<DocumentNode id={self.id} path={self.path!r} "
            f"depth={self.depth} leaf={self.is_leaf}>"
        )


# ---------------------------------------------------------------------------
# PageIndexEntry — book-style inverted index
# ---------------------------------------------------------------------------


class PageIndexEntry(Base):
    """
    One entry in the book-style page index.

    Maps a heading / keyword term to the DocumentNode that covers it,
    including the page range. The FastAPI `/index` page renders all entries
    for a document sorted alphabetically, exactly like a book's back-index.
    """

    __tablename__ = "page_index_entries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    doc_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    node_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("document_nodes.id", ondelete="CASCADE"), nullable=False
    )
    term: Mapped[str] = mapped_column(String(512), nullable=False)
    page_start: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    page_end: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    path: Mapped[str] = mapped_column(String(512), nullable=False)

    __table_args__ = (
        Index("ix_pie_doc_term", "doc_id", "term"),
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "doc_id": self.doc_id,
            "node_id": self.node_id,
            "term": self.term,
            "page_start": self.page_start,
            "page_end": self.page_end,
            "path": self.path,
        }


# ---------------------------------------------------------------------------
# Storage Engine
# ---------------------------------------------------------------------------


class StorageEngine:
    """
    Async SQLAlchemy engine wrapper.

    Usage::

        engine = await StorageEngine.create("sqlite+aiosqlite:///apex.db")
        async with engine.session() as session:
            nodes = await engine.get_children(session, parent_id=1)
    """

    def __init__(self, engine: AsyncEngine, session_factory: async_sessionmaker[AsyncSession]) -> None:
        self._engine = engine
        self._session_factory = session_factory

    # -- Factory ------------------------------------------------------------

    @classmethod
    async def create(
        cls,
        db_url: str = "sqlite+aiosqlite:///apex.db",
        *,
        echo: bool = False,
        pool_size: int = 10,
        max_overflow: int = 20,
    ) -> "StorageEngine":
        """
        Async factory — creates the engine and ensures schema exists.

        Args:
            db_url:       SQLAlchemy async URL.
                          SQLite:   ``sqlite+aiosqlite:///./apex.db``
                          Postgres: ``postgresql+asyncpg://user:pass@host/db``
            echo:         Enable SQL query logging (dev only).
            pool_size:    Connection pool size (ignored for SQLite).
            max_overflow: Max overflow connections (ignored for SQLite).
        """
        is_sqlite = db_url.startswith("sqlite")

        engine_kwargs: dict[str, Any] = {"echo": echo}
        if not is_sqlite:
            engine_kwargs["pool_size"] = pool_size
            engine_kwargs["max_overflow"] = max_overflow
            engine_kwargs["pool_pre_ping"] = True

        engine = create_async_engine(db_url, **engine_kwargs)

        # Enable WAL mode for SQLite — much better concurrent read performance
        if is_sqlite:

            @event.listens_for(engine.sync_engine, "connect")
            def set_wal_mode(dbapi_conn: Any, _: Any) -> None:
                dbapi_conn.execute("PRAGMA journal_mode=WAL")
                dbapi_conn.execute("PRAGMA synchronous=NORMAL")
                dbapi_conn.execute("PRAGMA foreign_keys=ON")

        session_factory = async_sessionmaker(
            engine, class_=AsyncSession, expire_on_commit=False
        )

        instance = cls(engine, session_factory)
        await instance._create_schema()
        logger.info("StorageEngine ready: %s", db_url.split("?")[0])
        return instance

    # -- Schema management --------------------------------------------------

    async def _create_schema(self) -> None:
        """Create all tables if they don't already exist."""
        async with self._engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)

    async def drop_schema(self) -> None:
        """Drop all ApexRAG tables — use with caution in tests only."""
        async with self._engine.begin() as conn:
            await conn.run_sync(Base.metadata.drop_all)

    async def dispose(self) -> None:
        """Release all pooled connections."""
        await self._engine.dispose()

    # -- Session context manager --------------------------------------------

    @asynccontextmanager
    async def session(self) -> AsyncGenerator[AsyncSession, None]:
        """Yield a managed async session with automatic rollback on error."""
        async with self._session_factory() as sess:
            try:
                yield sess
                await sess.commit()
            except Exception:
                await sess.rollback()
                raise

    # -- CRUD Operations ----------------------------------------------------

    async def insert_node(self, session: AsyncSession, node: DocumentNode) -> DocumentNode:
        """Persist a new DocumentNode and flush to get its generated ID."""
        session.add(node)
        await session.flush()
        await session.refresh(node)
        return node

    async def get_node(self, session: AsyncSession, node_id: int) -> DocumentNode | None:
        """Fetch a single node by primary key."""
        return await session.get(DocumentNode, node_id)

    async def get_children(
        self, session: AsyncSession, parent_id: int | None, doc_id: str | None = None
    ) -> Sequence[DocumentNode]:
        """
        Return all direct children of a node, ordered by position.

        If parent_id is None, returns root nodes (filtered by doc_id when given).
        """
        stmt = select(DocumentNode).where(DocumentNode.parent_id == parent_id)
        if doc_id:
            stmt = stmt.where(DocumentNode.doc_id == doc_id)
        stmt = stmt.order_by(DocumentNode.position)
        result = await session.execute(stmt)
        return result.scalars().all()

    async def get_subtree_path(
        self, session: AsyncSession, path_prefix: str, doc_id: str
    ) -> Sequence[DocumentNode]:
        """
        Return all nodes whose path starts with `path_prefix` for a given doc.
        Useful for bulk-loading subtrees.
        """
        stmt = (
            select(DocumentNode)
            .where(
                DocumentNode.doc_id == doc_id,
                DocumentNode.path.like(f"{path_prefix}%"),
            )
            .order_by(DocumentNode.path)
        )
        result = await session.execute(stmt)
        return result.scalars().all()

    async def update_summary(
        self, session: AsyncSession, node_id: int, summary: str
    ) -> None:
        """Update the Semantic Map summary of a specific node."""
        node = await self.get_node(session, node_id)
        if node:
            node.summary = summary

    async def list_documents(self, session: AsyncSession) -> Sequence[str]:
        """Return all unique doc_ids stored in the database."""
        stmt = select(DocumentNode.doc_id).distinct()
        result = await session.execute(stmt)
        return result.scalars().all()

    async def get_full_tree(
        self, session: AsyncSession, doc_id: str
    ) -> Sequence[DocumentNode]:
        """
        Return ALL nodes for a document ordered by path.
        Used by the FastAPI index page to render the complete tree.
        """
        stmt = (
            select(DocumentNode)
            .where(DocumentNode.doc_id == doc_id)
            .order_by(asc(DocumentNode.path))
        )
        result = await session.execute(stmt)
        return result.scalars().all()

    async def get_document_stats(self, session: AsyncSession, doc_id: str) -> dict[str, Any]:
        """Return aggregate stats for a document: node count, leaf count, max depth."""
        from sqlalchemy import func
        stmt = select(
            func.count(DocumentNode.id).label("total_nodes"),
            func.max(DocumentNode.depth).label("max_depth"),
            func.sum(
                # count leaf nodes: content IS NOT NULL
                # SQLAlchemy-agnostic way via case
                __import__("sqlalchemy").case(
                    (DocumentNode.content.isnot(None), 1), else_=0
                )
            ).label("leaf_count"),
        ).where(DocumentNode.doc_id == doc_id)
        result = await session.execute(stmt)
        row = result.one()
        return {
            "doc_id": doc_id,
            "total_nodes": row.total_nodes or 0,
            "max_depth": row.max_depth or 0,
            "leaf_count": row.leaf_count or 0,
        }

    # -- Page Index CRUD ----------------------------------------------------

    async def insert_page_index_entry(
        self, session: AsyncSession, entry: PageIndexEntry
    ) -> PageIndexEntry:
        session.add(entry)
        await session.flush()
        return entry

    async def get_page_index(
        self, session: AsyncSession, doc_id: str
    ) -> Sequence[PageIndexEntry]:
        """Return all page index entries for a doc, sorted alphabetically by term."""
        stmt = (
            select(PageIndexEntry)
            .where(PageIndexEntry.doc_id == doc_id)
            .order_by(asc(PageIndexEntry.term))
        )
        result = await session.execute(stmt)
        return result.scalars().all()

    async def search_page_index(
        self, session: AsyncSession, doc_id: str, query: str
    ) -> Sequence[PageIndexEntry]:
        """Full text search over page index terms (case-insensitive LIKE)."""
        stmt = (
            select(PageIndexEntry)
            .where(
                PageIndexEntry.doc_id == doc_id,
                PageIndexEntry.term.ilike(f"%{query}%"),
            )
            .order_by(asc(PageIndexEntry.term))
        )
        result = await session.execute(stmt)
        return result.scalars().all()

    async def delete_document(self, session: AsyncSession, doc_id: str) -> int:
        """
        Delete all nodes and page index entries for a document.
        Returns the number of nodes deleted.
        """
        # Delete page index entries first (FK)
        pie_stmt = select(PageIndexEntry).where(PageIndexEntry.doc_id == doc_id)
        pie_result = await session.execute(pie_stmt)
        for entry in pie_result.scalars().all():
            await session.delete(entry)

        stmt = select(DocumentNode).where(DocumentNode.doc_id == doc_id)
        result = await session.execute(stmt)
        nodes = result.scalars().all()
        count = len(nodes)
        for node in nodes:
            await session.delete(node)
        logger.info("Deleted %d nodes for doc_id=%r", count, doc_id)
        return count
